version: "3.1"

services:
  myjenkins:
    build:
      context: .
    image: myjenkins
    ports:
     - "8080:8080"
    depends_on:
     - mysonar
     - artifactory
    links:
      - mysonar
      - artifactory
    volumes:
     - "./jenkins_home:/var/jenkins_home/"
     - "./m2deps:/var/jenkins_home/.m2/repository/"
     - "./downloads:/var/jenkins_home/downloads"
     - "/var/run/docker.sock:/var/run/docker.sock"
    secrets:
     - artifactoryPassword
    #entrypoint: docker
    #command: ps
  mysonar:
    image: sonarqube:6.3.1
    ports:
     - "9000:9000"
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:5.4.4
    ports:
     - "8081:8081"

secrets:
  artifactoryPassword:
    file: ./secrets/artifactoryPassword
